name: Build
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"
      - name: Test
        run: export AWS_REGION="us-east-1" && sbt -v -Dfile.encoding=UTF-8 +test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'target/test-reports/TEST-*.xml'
      - name: Assembly
        run: sbt -v -Dfile.encoding=UTF-8 +assembly
