
name: Publish SHA

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Image SHA
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"
      - name: Assembly
        run: sbt -v -Dfile.encoding=UTF-8 +assembly
      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/id-service
          tag_format: "{sha}-{timestamp}"
