
name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"
      - name: Assembly
        run: sbt -v -Dfile.encoding=UTF-8 +assembly
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Publish the image
        run: ./push_image.sh
